---
title: "EDA and Models cm3341"
author: "Carolina Montes Garcia"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(janitor)
library(corrplot)

knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

```

# Import and Clean data
```{r}
load("data/dat1.RData")
dat1 = dat1 %>% clean_names() %>% na.omit()
```

# Categorical vars: gender, race, smoking, diabetes, hypertension.
```{r}
dat1_relabeled = dat1 %>%
  mutate(
    gender = factor(gender, levels = c(0, 1), labels = c("Female", "Male")),
    race = factor(race, levels = c(1, 2, 3, 4), labels = c("White", "Asian", "Black", "Hispanic")),
    smoking = factor(smoking, levels = c(0, 1, 2), labels = c("Never", "Former", "Current")),
    diabetes = factor(diabetes, levels = c(0, 1), labels = c("No", "Yes")),
    hypertension = factor(hypertension, levels = c(0, 1), labels = c("No", "Yes"))
  )
```

# Create bar plots
```{r}
p_gender = ggplot(dat1, aes(x = gender)) + geom_bar(fill = "skyblue") + labs(title = "Gender Distribution", x = "Gender", y = "Count")

p_race = ggplot(dat1, aes(x = race)) + geom_bar(fill= "orange") + labs(title = "Race/Ethnicity Distribution", x = "Race/Ethnicity", y = "Count")

p_smoking = ggplot(dat1, aes(x = smoking)) + geom_bar(fill = "skyblue") + labs(title = "Smoking Status", x = "Smoking", y = "Count")

p_diabetes = ggplot(dat1, aes(x = diabetes)) + geom_bar(fill = "orange") + labs(title = "Diabetes Status", x = "Diabetes", y = "Count")

p_hypertension = ggplot(dat1, aes(x = hypertension)) + geom_bar(fill = "skyblue") + labs(title = "Hypertension Status", x = "Hypertension", y = "Count")

(p_gender | p_race) /
(p_smoking | p_diabetes) /
(p_hypertension | plot_spacer())

barplot_combined = (p_gender | p_race) /
                    (p_smoking | p_diabetes) /
                    (p_hypertension | plot_spacer())

```

# Create correlation plot

```{r}
x = model.matrix(log_antibody ~ ., data = dat1)[, -1]
y = dat1$log_antibody
```

```{r}
corrplot::corrplot(cor(x), method = "circle", type = "full", tl.cex = 0.3)

```
## There do not seem to be a great deal of highly correlated predictors. I see a lot of empty white boxes, leading me to think that with this dataset I will not have to deal with many groups of highly correlated predictors. 


